version: '0'
services:
  app:
    container_name: bsb
    image: barrosod/bsb
    restart: always
    environment:
    - APPLICATION_URL=
    - GDRIVE_CLIENT_ID=<gdrive_client>
    - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    - DROPBOX_CLIENT_ID=<dropbox_key>
    ports:
    - "8334:8334"
